import subprocess
import json
import os
from fastapi import FastAPI
from pydantic import BaseModel
from fastapi.staticfiles import StaticFiles
import tempfile

# Import from our new geometric DSL modules
from parser import parse_ast
from core import eval_program, serialize_environment, export_polylogica_json

app = FastAPI()

# ---------- Pydantic Models ----------

class ProgramInput(BaseModel):
    program: str

class QueryInput(BaseModel):
    program: str  # Added DSL program input
    query: str

# ---------- API Routes ----------

@app.post("/run_program")
def run_program(data: ProgramInput):
    try:
        ast = parse_ast(data.program)
        env = eval_program(ast)
        return serialize_environment(env)
    except Exception as e:
        return {"success": False, "error": str(e)}
    
@app.post("/run_polylogica")
def run_polylogica(data: QueryInput):
    mesh_filename = "temp_mesh.json"
    query_filename = "query.imgql"
    result_filename = "result.json"  # The file generated by your working setup

    try:
        # 1. Compile the DSL to get the current environment
        try:
            ast = parse_ast(data.program)
            env = eval_program(ast)
        except Exception as dsl_error:
            return {"success": False, "error": f"DSL Compilation Error: {str(dsl_error)}"}

        # 2. Export the geometric mesh context to JSON
        export_polylogica_json(env, mesh_filename)

        # 3. Build the modified query text
        modified_query = f'load mesh = "{mesh_filename}"\n' + data.query

        # 4. Write to the query.imgql file
        with open(query_filename, "w", encoding="utf-8") as f:
            f.write(modified_query)

        # 5. Execute your functioning terminal configuration
        command = f"./linux-x64/PolyLogicA {query_filename}"
        
        current_env = os.environ.copy()
        
        process = subprocess.run(
            command,
            text=True,
            capture_output=True,
            check=False,
            shell=True,
            executable="/bin/bash",
            env=current_env
        )

        # If the binary crashes, bubble up the stderr diagnostic info
        if process.returncode != 0:
            error_msg = process.stderr.strip() or f"Process exited with code {process.returncode}\nOutput: {process.stdout.strip()}"
            return {"success": False, "error": error_msg}

        # 6. Read and parse the generated result.json file
        if os.path.exists(result_filename):
            with open(result_filename, "r", encoding="utf-8") as f:
                properties = json.load(f)
        else:
            # Fallback strategy: if it didn't create a file but dumped text to stdout instead
            stdout_content = process.stdout.strip()
            try:
                properties = json.loads(stdout_content)
            except json.JSONDecodeError:
                return {"success": False, "error": f"Could not find {result_filename} or parse stdout."}

        # 7. Deliver the structured properties dictionary right back to your frontend framework
        return {
            "success": True,
            "properties": properties
        }

    except Exception as e:
        return {
            "success": False,
            "error": f"Server Core Error: {str(e)}"
        }
    
# ---------- Static Files Mounting ----------
app.mount("/", StaticFiles(directory="web/frontend", html=True), name="frontend")